In [1]:
import pandas as pd
# import matplotlib.pyplot as plt
import yaml
import os
import glob

import sys
sys.path.append('../')
from utils import *

In [2]:
with open("../config.yaml", "r") as yamlfile:
    cfg = yaml.safe_load(yamlfile)

for section in cfg:
    RANDOM_STATE_SEED = cfg["variables"]["RANDOM_STATE_SEED"]
    THRESHOLD = cfg["variables"]["THRESHOLD"]
    THRESHOLD_LOSS = cfg["variables"]["THRESHOLD_LOSS"]

    PROCESSED_DATA_DIR = cfg["data_path"]["PROCESSED_DATA_DIR"]

DATA_DIR = 'D:/code/gr1/data/unraveled/data/network_flows'

In [3]:
dataset_paths = [os.path.join(DATA_DIR,  dataset_path) for dataset_path in os.listdir(DATA_DIR)]
all_csv_files = []
for dataset_path in dataset_paths:
    csv_files_directory = glob.glob(dataset_path + '/*.csv')
    all_csv_files.extend(csv_files_directory)

In [4]:
all_csv_files = ['D:/code/gr1/data/unraveled/data/network_flows/Week1_Day1-2_05262021-05272021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day1-2_05262021-05272021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day1-2_05262021-05272021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day1-2_05262021-05272021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day1-2_05262021-05272021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day3_05282021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day3_05282021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day3_05282021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day3_05282021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day3_05282021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day4_05292021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day4_05292021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day4_05292021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day4_05292021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day4_05292021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day5_05302021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day5_05302021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day5_05302021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day5_05302021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week1_Day5_05302021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day1_05312021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day1_05312021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day1_05312021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day1_05312021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day1_05312021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day2_06012021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day2_06012021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day2_06012021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day2_06012021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day2_06012021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day2_06012021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day3_06022021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day3_06022021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day3_06022021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day3_06022021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day3_06022021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day3_06022021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day4_06032021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day4_06032021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day4_06032021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day4_06032021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day4_06032021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day4_06032021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day5-7_06042021-06062021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day5-7_06042021-06062021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day5-7_06042021-06062021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day5-7_06042021-06062021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day5-7_06042021-06062021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week2_Day5-7_06042021-06062021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day1_06072021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day1_06072021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day1_06072021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day1_06072021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day1_06072021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day1_06072021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day2_06082021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day2_06082021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day2_06082021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day2_06082021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day2_06082021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day2_06082021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day3_06092021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day3_06092021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day3_06092021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day3_06092021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day3_06092021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day3_06092021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day4_06102021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day5-7_06112021-06132021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day5-7_06112021-06132021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day5-7_06112021-06132021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day5-7_06112021-06132021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day5-7_06112021-06132021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week3_Day5-7_06112021-06132021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day03_06162021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day03_06162021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day03_06162021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day03_06162021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day03_06162021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day03_06162021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day1_06152021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day1_06152021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day1_06152021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day1_06152021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day1_06152021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day1_06152021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day2_06152021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day2_06152021/net1011x_Week4_Day2_06152021_part_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day2_06152021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day2_06152021/net1012x_Week4_Day2_06152021_part_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day2_06152021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day2_06152021/net1013x_Week4_Day2_06152021_part_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day2_06152021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day2_06152021/net1014x_Week4_Day2_06152021_part_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day2_06152021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day2_06152021/net1015x_Week4_Day2_06152021_part_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day2_06152021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day3_7_06162021_06202021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day3_7_06162021_06202021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day3_7_06162021_06202021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day3_7_06162021_06202021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day3_7_06162021_06202021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day3_7_06162021_06202021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day4_06172021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day4_06172021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day4_06172021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day4_06172021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day4_06172021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week4_Day4_06172021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day1_06212021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day1_06212021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day1_06212021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day1_06212021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day1_06212021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day1_06212021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day2_06222021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day2_06222021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day2_06222021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day2_06222021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day2_06222021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day3_06232021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day3_06232021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day3_06232021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day3_06232021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day3_06232021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day3_06232021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day4_06242021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day4_06242021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day4_06242021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day4_06242021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day5-6_06252021-06262021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day5-6_06252021-06262021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day5-6_06252021-06262021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day5-6_06252021-06262021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day5-6_06252021-06262021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day5-6_06252021-06262021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day6_06272021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day6_06272021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day6_06272021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day6_06272021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day6_06272021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week5_Day6_06272021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day2_06292021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day2_06292021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day2_06292021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day2_06292021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day2_06292021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day2_06292021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day3_06302021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day3_06302021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day3_06302021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day3_06302021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day3_06302021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day3_06302021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day4_07012021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day4_07012021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day4_07012021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day4_07012021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day4_07012021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day4_07012021/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day5_07022021_part1/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day5_07022021_part2/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day5_07022021_part2/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day5_07022021_part2/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day5_07022021_part2/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day5_07022021_part2/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day5_07022021_part2/netgw_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day6-7_07032021-07042021/net1011x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day6-7_07032021-07042021/net1012x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day6-7_07032021-07042021/net1013x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day6-7_07032021-07042021/net1014x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day6-7_07032021-07042021/net1015x_Flow_labeled.csv', 'D:/code/gr1/data/unraveled/data/network_flows/Week6_Day6-7_07032021-07042021/netgw_Flow_labeled.csv'];

In [5]:
# all_dataframes = {}

if not os.path.exists(PROCESSED_DATA_DIR):
    os.mkdir(PROCESSED_DATA_DIR)

In [6]:
print(f'Number of apt2021 files: {len(all_csv_files)}')


Number of apt2021 files: 173


In [7]:
apt_files = []

def get_apt_files(csv_file, threshold):
    try:
        # Đọc tệp CSV với low_memory=False để xử lý kiểu dữ liệu hỗn hợp
        df = pd.read_csv(csv_file, on_bad_lines='skip', low_memory=False)
        if 'Stage' in df.columns and 'Benign' in df['Stage'].value_counts():
            # Tính phần trăm của các trường hợp 'Benign' và so sánh với ngưỡng
            benign_percentage = (df['Stage'].value_counts()['Benign'] / len(df)) * 100
            if benign_percentage < threshold:
                print(f'Tệp: {csv_file}')
                apt_files.append(csv_file)
                print('-------------------------------------------------------------------------')
    except pd.errors.ParserError as e:
        print(f'Lỗi phân tích cú pháp {csv_file}: {e}')
    except Exception as e:
        print(f'Lỗi không mong đợi với {csv_file}: {e}')



In [8]:
# Xử lý từng tệp CSV để tìm các tệp APT
for csv_file in all_csv_files:
    get_apt_files(csv_file, threshold=99)

Tệp: D:/code/gr1/data/unraveled/data/network_flows/Week5_Day1_06212021/net1013x_Flow_labeled.csv
-------------------------------------------------------------------------
Tệp: D:/code/gr1/data/unraveled/data/network_flows/Week5_Day2_06222021/net1013x_Flow_labeled.csv
-------------------------------------------------------------------------
Tệp: D:/code/gr1/data/unraveled/data/network_flows/Week5_Day2_06222021/netgw_Flow_labeled.csv
-------------------------------------------------------------------------
Tệp: D:/code/gr1/data/unraveled/data/network_flows/Week5_Day3_06232021/net1013x_Flow_labeled.csv
-------------------------------------------------------------------------
Tệp: D:/code/gr1/data/unraveled/data/network_flows/Week5_Day3_06232021/netgw_Flow_labeled.csv
-------------------------------------------------------------------------
Tệp: D:/code/gr1/data/unraveled/data/network_flows/Week5_Day4_06242021/net1013x_Flow_labeled.csv
------------------------------------------------------

In [9]:
print(len(apt_files))

23


In [10]:
df_temp = []
problematic_files = []

for file_path in all_csv_files:
    try:
        # Sử dụng on_bad_lines='skip' để bỏ qua các dòng lỗi
        df_temp.append(pd.read_csv(file_path, low_memory=False, on_bad_lines='skip'))
    except pd.errors.ParserError as e:
        print(f"Error reading {file_path}: {e}")
        problematic_files.append(file_path)

# Kiểm tra xem có tệp nào gặp lỗi không
if problematic_files:
    print("These files encountered parsing errors:", problematic_files)

# Gộp các DataFrame đã được đọc thành công
df = pd.concat(df_temp, ignore_index=True)

# In ra số lượng dòng trong DataFrame đã gộp
print(len(df))

6829045


In [11]:
print(df.head(5))

   Unnamed: 0  id  expiration_id     src_ip            src_mac   src_oui  \
0         0.0   0              0  10.1.1.11  fa:16:3e:2c:fe:de  fa:16:3e   
1         1.0   1              0   10.1.1.4  fa:16:3e:03:f9:45  fa:16:3e   
2         2.0   2              0   10.1.1.6  fa:16:3e:d9:a8:74  fa:16:3e   
3         3.0   3              0   10.1.1.4  fa:16:3e:03:f9:45  fa:16:3e   
4         4.0   4              0   10.1.1.6  fa:16:3e:d9:a8:74  fa:16:3e   

   src_port          dst_ip            dst_mac   dst_oui  ...  \
0     47794   35.232.111.17  fa:16:3e:e5:11:55  fa:16:3e  ...   
1       123  138.236.128.36  fa:16:3e:e5:11:55  fa:16:3e  ...   
2       123  27.124.125.252  fa:16:3e:e5:11:55  fa:16:3e  ...   
3       123   45.79.214.107  fa:16:3e:e5:11:55  fa:16:3e  ...   
4       123   204.11.201.12  fa:16:3e:e5:11:55  fa:16:3e  ...   

   application_is_guessed          requested_server_name  client_fingerprint  \
0                       0  connectivity-check.ubuntu.com                

In [12]:
df = df[df['Stage'] != 'Normal']
print(df['Stage'].value_counts())

Stage
Benign                6731804
Reconnaissance          34794
Lateral Movement        27445
Establish Foothold      27118
Data Exfiltration        7522
Cover up                  362
Name: count, dtype: int64


In [13]:
# Display unique values in the 'stage' column
unique_stages = df['Stage'].unique()
print("Unique values in the 'stage' column:", unique_stages)

Unique values in the 'stage' column: ['Benign' 'Lateral Movement' 'Reconnaissance' 'Data Exfiltration'
 'Establish Foothold' 'Cover up']


In [14]:
list_features = [
    'bidirectional_duration_ms', 'src2dst_duration_ms',
    'dst2src_duration_ms', 'src2dst_packets', 'dst2src_packets',
    'src2dst_bytes', 'dst2src_bytes', 'src2dst_max_ps', 'src2dst_min_ps',
    'src2dst_mean_ps', 'src2dst_stddev_ps', 'dst2src_max_ps', 'dst2src_min_ps',
    'dst2src_mean_ps', 'dst2src_stddev_ps', 'bidirectional_mean_piat_ms',
    'bidirectional_stddev_piat_ms', 'bidirectional_max_piat_ms', 
    'bidirectional_min_piat_ms','src2dst_mean_piat_ms', 'src2dst_stddev_piat_ms', 
    'src2dst_max_piat_ms', 'src2dst_min_piat_ms', 'dst2src_mean_piat_ms',
    'dst2src_stddev_piat_ms', 'dst2src_max_piat_ms', 'dst2src_min_piat_ms', 
    'bidirectional_fin_packets', 'src2dst_fin_packets', 'dst2src_fin_packets', 
    'bidirectional_syn_packets', 'src2dst_syn_packets', 'dst2src_syn_packets',
    'bidirectional_rst_packets', 'src2dst_rst_packets', 'dst2src_rst_packets',
    'bidirectional_psh_packets', 'src2dst_psh_packets', 'dst2src_psh_packets', 
    'bidirectional_ack_packets', 'src2dst_ack_packets', 'dst2src_ack_packets', 
    'bidirectional_urg_packets', 'src2dst_urg_packets', 'dst2src_urg_packets',
    'bidirectional_cwr_packets', 'src2dst_cwr_packets', 'dst2src_cwr_packets', 
    'bidirectional_ece_packets', 'src2dst_ece_packets', 'dst2src_ece_packets',
    'DefenderResponse', 'Stage'
]

df = df[list_features]

In [15]:
# df = pd.read_csv('C:/Users/Admin/Desktop/DATN/DATA/Unraveled_DATA2/W5_D6/net3.csv',on_bad_lines='skip')
cols_unique_val = []

# Dropping features contain unique value for every instance
# for i in range (1,3):
for col in df.columns:
    if df[col].nunique() == 1:
        cols_unique_val.append(col)
        
print(f'Features contain unique value for every instance: {cols_unique_val}')
df.drop(cols_unique_val, axis=1, inplace=True)

Features contain unique value for every instance: ['dst2src_urg_packets', 'dst2src_cwr_packets', 'dst2src_ece_packets']


In [16]:
import pandas as pd

# Giả sử stage_mapping là từ điển mà bạn đã định nghĩa
stage_mapping = {
    'Benign': 1,        
    'Reconnaissance': 2,     
    'Establish Foothold': 3,
    'Lateral Movement': 4,
    'Data Exfiltration': 5,
    'Cover up': 6
}

print(df.columns)

# Giả sử df là DataFrame đã đọc từ một tập tin CSV và có cột 'Stage'
# In ra các giá trị duy nhất trong cột 'Stage'
unique_stages = df['Stage'].unique()
print(f"Các giá trị duy nhất trong cột 'Stage': {unique_stages}")


Index(['bidirectional_duration_ms', 'src2dst_duration_ms',
       'dst2src_duration_ms', 'src2dst_packets', 'dst2src_packets',
       'src2dst_bytes', 'dst2src_bytes', 'src2dst_max_ps', 'src2dst_min_ps',
       'src2dst_mean_ps', 'src2dst_stddev_ps', 'dst2src_max_ps',
       'dst2src_min_ps', 'dst2src_mean_ps', 'dst2src_stddev_ps',
       'bidirectional_mean_piat_ms', 'bidirectional_stddev_piat_ms',
       'bidirectional_max_piat_ms', 'bidirectional_min_piat_ms',
       'src2dst_mean_piat_ms', 'src2dst_stddev_piat_ms', 'src2dst_max_piat_ms',
       'src2dst_min_piat_ms', 'dst2src_mean_piat_ms', 'dst2src_stddev_piat_ms',
       'dst2src_max_piat_ms', 'dst2src_min_piat_ms',
       'bidirectional_fin_packets', 'src2dst_fin_packets',
       'dst2src_fin_packets', 'bidirectional_syn_packets',
       'src2dst_syn_packets', 'dst2src_syn_packets',
       'bidirectional_rst_packets', 'src2dst_rst_packets',
       'dst2src_rst_packets', 'bidirectional_psh_packets',
       'src2dst_psh_packets', 

In [17]:
stage_mapping = {
    'Benign': 0,        
    'Detected': 1,     
}

df['DefenderResponse'] = df['DefenderResponse'].map(stage_mapping)

Data cleaning

In [18]:
import numpy as np


# df.value_counts('Stage')
df.replace([-np.inf, np.inf], np.nan, inplace=True)
df.fillna(0, inplace=True)

# Dropping duplicate samples
df.drop_duplicates(inplace=True)
df.value_counts('DefenderResponse')

DefenderResponse
0    2620063
1      11989
Name: count, dtype: int64

In [19]:
df.to_csv('D:/code/gr1/data/dataset/unraveled_defender_response.csv')

Using data

In [5]:
import pandas as pd

df = pd.read_csv('D:/code/gr1/data/dataset/unraveled_defender_response.csv')

In [6]:
import pandas as pd

# Giả sử stage_mapping là từ điển mà bạn đã định nghĩa
stage_mapping = {
    'Benign': 0,        
    'Reconnaissance': 1,     
    'Establish Foothold': 2,
    'Lateral Movement': 3,
    'Data Exfiltration': 4,
    'Cover up': 5
}

print(df.columns)

# Giả sử df là DataFrame đã đọc từ một tập tin CSV và có cột 'Stage'
# In ra các giá trị duy nhất trong cột 'Stage'
unique_stages = df['Stage'].unique()
print(f"Các giá trị duy nhất trong cột 'Stage': {unique_stages}")


Index(['Unnamed: 0', 'bidirectional_duration_ms', 'src2dst_duration_ms',
       'dst2src_duration_ms', 'src2dst_packets', 'dst2src_packets',
       'src2dst_bytes', 'dst2src_bytes', 'src2dst_max_ps', 'src2dst_min_ps',
       'src2dst_mean_ps', 'src2dst_stddev_ps', 'dst2src_max_ps',
       'dst2src_min_ps', 'dst2src_mean_ps', 'dst2src_stddev_ps',
       'bidirectional_mean_piat_ms', 'bidirectional_stddev_piat_ms',
       'bidirectional_max_piat_ms', 'bidirectional_min_piat_ms',
       'src2dst_mean_piat_ms', 'src2dst_stddev_piat_ms', 'src2dst_max_piat_ms',
       'src2dst_min_piat_ms', 'dst2src_mean_piat_ms', 'dst2src_stddev_piat_ms',
       'dst2src_max_piat_ms', 'dst2src_min_piat_ms',
       'bidirectional_fin_packets', 'src2dst_fin_packets',
       'dst2src_fin_packets', 'bidirectional_syn_packets',
       'src2dst_syn_packets', 'dst2src_syn_packets',
       'bidirectional_rst_packets', 'src2dst_rst_packets',
       'dst2src_rst_packets', 'bidirectional_psh_packets',
       'src2dst_

In [7]:
df['Stage'] = df['Stage'].map(stage_mapping)
unique_stages = df['Stage'].unique()
print(f"Các giá trị duy nhất trong cột 'Stage': {unique_stages}")

Các giá trị duy nhất trong cột 'Stage': [0 3 1 4 2 5]


In [8]:
df.columns

Index(['Unnamed: 0', 'bidirectional_duration_ms', 'src2dst_duration_ms',
       'dst2src_duration_ms', 'src2dst_packets', 'dst2src_packets',
       'src2dst_bytes', 'dst2src_bytes', 'src2dst_max_ps', 'src2dst_min_ps',
       'src2dst_mean_ps', 'src2dst_stddev_ps', 'dst2src_max_ps',
       'dst2src_min_ps', 'dst2src_mean_ps', 'dst2src_stddev_ps',
       'bidirectional_mean_piat_ms', 'bidirectional_stddev_piat_ms',
       'bidirectional_max_piat_ms', 'bidirectional_min_piat_ms',
       'src2dst_mean_piat_ms', 'src2dst_stddev_piat_ms', 'src2dst_max_piat_ms',
       'src2dst_min_piat_ms', 'dst2src_mean_piat_ms', 'dst2src_stddev_piat_ms',
       'dst2src_max_piat_ms', 'dst2src_min_piat_ms',
       'bidirectional_fin_packets', 'src2dst_fin_packets',
       'dst2src_fin_packets', 'bidirectional_syn_packets',
       'src2dst_syn_packets', 'dst2src_syn_packets',
       'bidirectional_rst_packets', 'src2dst_rst_packets',
       'dst2src_rst_packets', 'bidirectional_psh_packets',
       'src2dst_

In [9]:
df.drop('Unnamed: 0', axis=1, inplace=True)
df.value_counts('Stage')

Stage
0    2559802
3      27272
2      27095
1      11989
4       5535
5        359
Name: count, dtype: int64

In [10]:
import pandas as pd

# Giả sử dữ liệu của bạn là df
# Lấy tất cả các mẫu không có nhãn là 0
df_other = df[df['Stage'] != 0]

# Lấy ngẫu nhiên 50,000 mẫu có nhãn là 0
df_stage_0 = df[df['Stage'] == 0].sample(n=50000, random_state=42)

# Kết hợp lại hai DataFrame
df_reduced = pd.concat([df_other, df_stage_0])

# Kiểm tra lại số lượng mẫu sau khi giảm
print(df_reduced['Stage'].value_counts())


Stage
0    50000
3    27272
2    27095
1    11989
4     5535
5      359
Name: count, dtype: int64


<h2> Training ATTACK</h2>

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report


In [12]:
X_train = df.drop('Stage', axis=1)
Y_train = df['Stage']

# x_train = df.iloc[:, :-1].values
# y_train = df.iloc[:, -1].values


x_train, x_test, y_train, y_test = train_test_split(X_train, Y_train, stratify=Y_train, test_size=0.1, random_state=42)

In [13]:
random_forest_apt2021 = RandomForestClassifier(
    n_estimators=100,
    n_jobs=12,
)

In [14]:
random_forest_apt2021.fit(x_train, y_train)

RandomForestClassifier(n_jobs=12)

In [32]:
list_ft = ['bidirectional_duration_ms', 'src2dst_duration_ms',
       'dst2src_duration_ms', 'src2dst_packets', 'dst2src_packets',
       'src2dst_bytes', 'dst2src_bytes', 'src2dst_max_ps', 'src2dst_min_ps',
       'src2dst_mean_ps', 'src2dst_stddev_ps', 'dst2src_max_ps',
       'dst2src_min_ps', 'dst2src_mean_ps', 'dst2src_stddev_ps',
       'bidirectional_mean_piat_ms', 'bidirectional_stddev_piat_ms',
       'bidirectional_max_piat_ms', 'bidirectional_min_piat_ms',
       'src2dst_mean_piat_ms', 'src2dst_stddev_piat_ms', 'src2dst_max_piat_ms',
       'src2dst_min_piat_ms', 'dst2src_mean_piat_ms', 'dst2src_stddev_piat_ms',
       'dst2src_max_piat_ms', 'dst2src_min_piat_ms',
       'bidirectional_fin_packets', 'src2dst_fin_packets',
       'dst2src_fin_packets', 'bidirectional_syn_packets',
       'src2dst_syn_packets', 'dst2src_syn_packets',
       'bidirectional_rst_packets', 'src2dst_rst_packets',
       'dst2src_rst_packets', 'bidirectional_psh_packets',
       'src2dst_psh_packets', 'dst2src_psh_packets',
       'bidirectional_ack_packets', 'src2dst_ack_packets',
       'dst2src_ack_packets', 'bidirectional_urg_packets',
       'src2dst_urg_packets']

df_test = pd.read_csv("D:/code/gr1/data/unraveled-test.csv")
df_test = df_test[list_ft]
df_test
df_test = df_test.values
y_test_pred = random_forest_apt2021.predict(df_test)
print(y_test_pred)

[0 3 2 1]


D:\code\python\code\ScoreFactor\.venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [15]:
from sklearn.metrics import accuracy_score, classification_report
y_pred = random_forest_apt2021.predict(x_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)


0.9795635357856584


In [49]:
df.value_counts('Stage')


Stage
0    2559802
3      27272
2      27095
1      11989
4       5535
5        359
Name: count, dtype: int64

In [16]:
f1 = f1_score(y_test, y_pred, average='weighted')
f2 = f1_score(y_test, y_pred, average='macro')
f3 = f1_score(y_test, y_pred, average='micro')
# accuracy3 = f1_score(y_test, y_pred, average='binary')
pr1 = precision_score(y_test, y_pred, average='weighted')
pr2 = precision_score(y_test, y_pred, average='macro')
pr3 = precision_score(y_test, y_pred, average='micro')

re1 = recall_score(y_test, y_pred, average='weighted')
re2 = recall_score(y_test, y_pred, average='macro')
re3 = recall_score(y_test, y_pred, average='micro')


print(f1)
print(f2)
print(f3)
print("---------------------")
print(pr1)
print(pr2)
print(pr3)
print("---------------------")

print(re1)
print(re2)
print(re3)


# print(accuracy3)

conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

0.9797020452979927
0.4158376202984799
0.9795635357856584
---------------------
0.9798425527920723
0.41570621336218005
0.9795635357856584
---------------------
0.9795635357856584
0.41611971538399617
0.9795635357856584
[[255790      0    131     25      9     26]
 [     0   1199      0      0      0      0]
 [    50      0    563   2095      1      1]
 [     7      0   2125    162    433      0]
 [     7      0      6    427    112      1]
 [    31      0      0      2      2      1]]


In [30]:
print(classification_report(y_test, y_pred))

                    precision    recall  f1-score   support

            Benign       1.00      1.00      1.00    255981
          Cover up       0.00      0.00      0.00        36
 Data Exfiltration       0.21      0.22      0.21       553
Establish Foothold       0.20      0.20      0.20      2710
  Lateral Movement       0.06      0.06      0.06      2727
    Reconnaissance       1.00      1.00      1.00      1199

          accuracy                           0.98    263206
         macro avg       0.41      0.41      0.41    263206
      weighted avg       0.98      0.98      0.98    263206


In [ ]:
<h1></h1>

In [17]:
import xgboost as xgb
xgb_apt2021 = xgb.XGBClassifier(objective='multi:softmax')

In [18]:
xgb_apt2021.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softmax', ...)

In [19]:
y_pred = xgb_apt2021.predict(x_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)


conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

print(classification_report(y_test, y_pred))

0.9880207897996246
[[255790      0    155      6     15     15]
 [     0   1199      0      0      0      0]
 [     3      0   2285    422      0      0]
 [     7      0   1981    315    424      0]
 [     5      0     49     33    464      2]
 [    16      0      0      0     20      0]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    255981
           1       1.00      1.00      1.00      1199
           2       0.51      0.84      0.64      2710
           3       0.41      0.12      0.18      2727
           4       0.50      0.84      0.63       553
           5       0.00      0.00      0.00        36

    accuracy                           0.99    263206
   macro avg       0.57      0.63      0.57    263206
weighted avg       0.99      0.99      0.99    263206


In [20]:
f1 = f1_score(y_test, y_pred, average='weighted')
f2 = f1_score(y_test, y_pred, average='macro')
f3 = f1_score(y_test, y_pred, average='micro')
# accuracy3 = f1_score(y_test, y_pred, average='binary')
pr1 = precision_score(y_test, y_pred, average='weighted')
pr2 = precision_score(y_test, y_pred, average='macro')
pr3 = precision_score(y_test, y_pred, average='micro')

re1 = recall_score(y_test, y_pred, average='weighted')
re2 = recall_score(y_test, y_pred, average='macro')
re3 = recall_score(y_test, y_pred, average='micro')


print(f1)
print(f2)
print(f3)
print("---------------------")
print(pr1)
print(pr2)
print(pr3)
print("---------------------")

print(re1)
print(re2)
print(re3)


# print(accuracy3)

conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

0.9864212029304202
0.5741047704804841
0.9880207897996246
---------------------
0.987512658715556
0.569950149657415
0.9880207897996246
---------------------
0.9880207897996246
0.6328330847106484
0.9880207897996246
[[255790      0    155      6     15     15]
 [     0   1199      0      0      0      0]
 [     3      0   2285    422      0      0]
 [     7      0   1981    315    424      0]
 [     5      0     49     33    464      2]
 [    16      0      0      0     20      0]]
